### ISSUE TITLE
YearWeek.parse(CharSequence,TemporalAccessor) failed on pattern formatter

### ISSUE THREAD

**Issue by chzhong** [ThreeTen/threeten-extra#142]
The following codes:
```
YearWeek.parse("2019-W01", DateTimeFormatter.ofPattern("YYYY-'W'ww"))
```
would failed with the following stack trace:
```
java.time.format.DateTimeParseException: Text '2019-W01' could not be parsed: Unable to obtain YearWeek from TemporalAccessor: {WeekOfWeekBasedYear[WeekFields[SUNDAY,1]]=1, WeekBasedYear[WeekFields[SUNDAY,1]]=2019},ISO of type java.time.format.Parsed
	at java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:1920)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1855)
Caused by: java.time.DateTimeException: Unable to obtain YearWeek from TemporalAccessor: {WeekOfWeekBasedYear[WeekFields[SUNDAY,1]]=1, WeekBasedYear[WeekFields[SUNDAY,1]]=2019},ISO of type java.time.format.Parsed
	at com.abc.spiderweb.view.util.YearWeek.from(YearWeek.java:241)
	at java.time.format.Parsed.query(Parsed.java:226)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1851)
	... 24 more
Caused by: java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: WeekBasedYear
	at java.time.temporal.IsoFields$Field$4.getFrom(IsoFields.java:528)
	at java.time.format.Parsed.getLong(Parsed.java:205)
```

Use YearWeek.parse(CharSequence) was fine. It seem it was the fault of JDK...

**Comment by jodastephen** [comment]
The parser requires the week fields associated with the ISO rules, ie. `IsoFields.WEEK_BASED_YEAR` and `IsoFields.WEEK_OF_WEEK_BASED_YEAR`. This code works fine:

        DateTimeFormatter f = new DateTimeFormatterBuilder()
                .appendValue(IsoFields.WEEK_BASED_YEAR, 4)
                .appendLiteral('-')
                .appendLiteral('W')
                .appendValue(IsoFields.WEEK_OF_WEEK_BASED_YEAR, 2)
                .toFormatter();
        YearWeek.parse("2019-W01", f);

**Comment by kalgon** [comment]
Is this the same reason why

    System.out.println(YearWeek.now().format(DateTimeFormatter.ofPattern("Y-w")));

throws 

    java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: DayOfWeek

? (`Y` being the week-based-year and `w` being the week-of-week-based-year)

**Comment by JensGabe** [comment]
Followup:
I can see that the reason a DateTimeFormatter.ofPattern("YYYY-'W'ww") will not parse to a YearWeek is beacuse the generic ofPattern(String) creates a Locale specific DTF, which results in WeekFields$ComputedDayOfField instances of the generic IsoFields.WEEK_BASED_YEAR and IsoFields.WEEK_OF_WEEK_BASED_YEAR.

I expect the reason YearWeek cannot work nicely (ie fallback) to the Locale specific versions, are because the specific locale is not known to the YearWeek methods when required. Or perhaps even more complex...

cannot deduce why the DTF does not simply result in the "raw" IsoField versions rather than the Locale specific ones, but I guess that is a question for the JSR-310 group and not here...

A locale aware version of the YearWeek class would be nice though using something like this:
```
// Note WeekFields.ISO does not play nice until Java 16: https://bugs.openjdk.java.net/browse/JDK-8233048
final WeekFields weekFields = WeekFields.of(formatter.getLocale());
if (temporal.isSupported(weekFields.weekBasedYear()) && temporal.isSupported(weekFields.weekOfWeekBasedYear()))
{
	int year = Math.toIntExact(temporal.getLong(weekFields.weekBasedYear()));
	int week = Math.toIntExact(temporal.getLong(weekFields.weekOfWeekBasedYear()));
	return YearWeek.of(year, week);
}
```
