### ISSUE TITLE
A zoneless time source for java.time

### ISSUE THREAD

**Issue by kluever** [ThreeTen/threeten-extra#150]
Every `java.time.Clock` also contains a time zone, and it can be freely used to produce zone-dependent values; as in `LocalDate.now(clock)`.  However, we've found that most users really just want zoneless `Instant`s (the zone component usually comes from the user session, not the server).

Inside of Google we have a `TimeSource` interface, that looks like this:
```java
public interface TimeSource {

  static TimeSource system() { ... }

  Instant now();

  default LocalDateTime now(ZoneId zoneId) { ... }

  default LocalDate today(ZoneId zoneId) { ... }

  default Clock asClock(ZoneId zoneId) { ... }
}
```

We strongly recommend its use over `java.time.Clock`, and its usage outnumbers `Clock` by 8x at this point.

We'd like to contribute this to threeten-extra, but a few obstacles:

1. we now have 30k+ references to our `TimeSource`, which makes migration very difficult (even for something as simple as a package/class rename).

2. threeten-extra already has a `TimeSource` interface in `org.threeten.extra.scale`. That interface is _nearly_ what we want, minus the `UtcInstant` and `TaiInstant`-returning methods. Do you see any path forward for harmonizing these interfaces? What are the stability guarantees for threeten-extra?

Thanks,
-Kurt (on behalf of Google's "GoodTime" team)

**Comment by Clockwork-Muse** [comment]
... is there a reason to avoid [`Clock.system(userSessionZone)`](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/time/Clock.html#system(java.time.ZoneId)) (or [`clock.withZone(userSessionZone)`](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/time/Clock.html#withZone(java.time.ZoneId)), more likely)?  Is it just to avoid a single object allocation?  Or to enforce not using the system zone?  The zone has no effect on the actual `Instant`s returned, so it could otherwise be safely used to get `Instant`s....

**Comment by kluever** [comment]
The fact that the zone is only _sometimes_ used when using a `Clock` ends up being extremely confusing.

`clock.instant().atZone(userSessionZone).toLocalDate()` is safe, but `LocalDate.now(clock)` is not.

It's extremely easy to forget to use the user session zone when operating with `Clock`. We feel like this was a major design flaw in `java.time.Clock`

**Comment by Clockwork-Muse** [comment]
What I was trying to get at was, can you change which instance of `Clock` they're getting?  Since you should be injecting the clock anyways, why isn't it one with the user-session-zone set?

Otherwise, ban `Whatever.now(clock)` in favor of [`Whatever.ofInstant(clock.instant(), userSessionZone)`](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/time/LocalDate.html#ofInstant(java.time.Instant,java.time.ZoneId)), maybe?

To go along with that, you could just inject a functor that returns only an instant: `Supplier<Instant>` or some such.

**Comment by kluever** [comment]
Well the `TimeSource` interface I specified in #1 above is basically a `Supplier<Instant>`. We did discuss having it implement `Supplier<Instant>` during our API review...here are some notes:

- \- Method references make it easy to adapt to one if necessary. (clock::now)
- \+ Our general rule for implementing functional types directly has been that, at a minimum, it must be abundantly obvious what the meaning of the thing is when used as that functional type. I think this probably fits that bill.
- \- It would have to have two methods, the real one above (e.g., `now()`), plus `get()`, and some users would call `get()`, so we'd end up doing the thing we do in other places and mark it deprecated - this is all just too weird.

**Comment by Clockwork-Muse** [comment]
> It would have to have two methods

... _why_?

**Comment by Clockwork-Muse** [comment]
Uh, no, you wouldn't bother implementing `Clock` in such a case, you'd just have things that would normally take a `Clock` just take the raw supplier.  That would make it so that the only such thing available would be the `Instant`, and avoid that particular set of issues

**Comment by jodastephen** [comment]
In principle, the idea of a `TimeSource` makes sense. However, I have concerns about the favouritism shown on your proposed interface re  `LocalDate` and `LocalDateTime`. Why not `LocalTime`, or `ZonedDateTime`? (Note that Java 9 added `ofInstant(Instant, ZonedId)` methods to the Local* date classes.)

Also JSR-310 naming would normally prefer `atZone(ZoneId)` to `asClock(ZoneId)`. or `toClock()` But maybe I can be persuaded on this.

For me, this interface makes sense:

```
public interface TimeSource {
  public static TimeSource system() { ... }
  public abstract Instant now();
  public default Clock atZone(ZoneId zoneId) { ... }
}
```

The problem is how to bind it to other temporal classes without picking favourites. Or perhaps it doesn't need to?

ThreeTen-Extra is intended to be as stable as Joda-Time, ie. things don't break. A `TimeSource` in the root package could exist alongside the one in the `scale` subpackage. Or a different name could be chosen. Potentially, the one in the `scale` subpackage could be renamed to `TimeScaleSource` with the existing `TimeSource` deprecated for removal, but I'd like to see if there are any other naming options.

* `InstantSupplier` ?
* `InstantProvider` ?
* `InstantSource` ?

**Comment by cpovirk** [comment]
As to favouritism:

For what it's worth: I wasn't around for the decision, but I personally have always felt uneasy about _any_ methods like `LocalDate today(ZoneId)`: I fear that they encourage users who want the current time in different objects/forms to read it more than once -- say, once to get a `LocalDate` and once to get a `LocalDateTime`. However, I haven't seen much evidence of this.

What I _have_ seen evidence of is APIs that should accept a fixed `Instant` but instead accept a `TimeSource` and then read it multiple times through the _same_ method each time. (For example, a class computes both `timeSource.today()` and `timeSource.today().minusDays(7)`, and the result isn't necessarily 7 days apart.) But note that that still leaves a large _absolute number_ of people who do need `TimeSource`, even if the fraction of "misuse" is high.

(Incidentally, we have general reservations about `ZonedDateTime`, which are probably worth discussing someday, even if they don't end up having a direct impact on any specific issue yet.)

**Comment by cpovirk** [comment]
As to the name:

Our concern with names of the form `InstantSupplier`, etc. was that they didn't clearly suggest that the instant that was being supplied was "now."

There are other clock-like words that we considered, like `Timepiece` (and I was thinking about `Timekeeper` after we made our decision). One concern with names like those is that they don't distinguish themselves clearly from `Clock`. But the same was true of `TimeSource`.

Ultimately, I think a big factor in our decision was that `TimeSource` was a name that several projects had independently chosen for this concept (and only one had chosen for a different concept). (OK, I'd consider the threeten-extra `TimeSource` to be "_mostly_ the same concept.")

**Comment by jodastephen** [comment]
How to proceed? I'm willing to add an interface (assuming no better name is found):

```
public interface TimeSource {
  public static TimeSource system() { ... }
  public abstract Instant now();
  public default Clock toClock(ZoneId zoneId) { ... }
}
```

Renaming (by deprecation) the interface in the scale subpackage.

But would this meet your requirements?

**Comment by kluever** [comment]
Hey Stephen,

Thanks for following up on this! I think we'd be happy with your proposal, but can you give me a week or two to discuss w/ my broader team (I'm out of office next week, so...).

Thanks again for your help on these!

-Kurt

**Comment by kluever** [comment]
Cross-linking to the [core-libs-dev thread](https://mail.openjdk.java.net/pipermail/core-libs-dev/2021-May/077213.html).

**Comment by mjustin** [comment]
Has this been completely superseded by `InstantSource` in Java 17?

**Comment by jodastephen** [comment]
Yes, InstantSource is the solution to this issue
