### ISSUE TITLE
Cache UtcInstant's toString() Value

### ISSUE THREAD

**Issue by stevenpaligo** [ThreeTen/threeten-extra#176]
`UtcInstant#toString()` is a pretty expensive call. If invoked multiple times on the same instance (e.g. logging an instant as it is passed around), it can take up a disproportionate amount of time. If using lots of instants the same way, it can get ridiculous.

Since the UtcInstant class is immutable, it shouldn't hurt to:

1. Save off the computed string the first time `toString()` is called
2. If `toString()` is called again, return the cached value

Please consider this. If you're willing to accept it, I can submit a PR.

**Comment by jodastephen** [comment]
I'm surprised you'd use `UtcInstant` for that, but fine if you do. The issue here is that `java.time.Instant` does not cache `toString`, nor do any of the other standard date/time classes. That would make this an odd special case.

Overall, I think it is just about worth doing. String is the most common way to access the data here, which just about justifies the extra memory use.

**Comment by stevenpaligo** [comment]
See PR #177

**Comment by jodastephen** [comment]
Closed by PR
