### ISSUE TITLE
Provide Jackson module

### ISSUE THREAD

**Issue by matthewadams** [ThreeTen/threeten-extra#190]
We use `Interval` in our app, and [Jackson](https://github.com/FasterXML/jackson) chokes on it.

Can you provide (perhaps in another repo) a [Jackson Module](https://github.com/FasterXML/jackson#third-party-datatype-modules) for the types defined in this library?

**Comment by erizzo** [comment]
Same here, but not just for `Interval` (obviously?).
On a related note, can anyone share custom ser/deser code they have for handing the ThreeTen types?

**Comment by jodastephen** [comment]
This is an open goal for someone who wants to write their own open source project. For the record, it's not differing I'm planning on working on.

**Comment by erizzo** [comment]
@jodastephen I'm curious why, with the ubiquity of Jackson, you'd not even consider adding support for usage with Jackson to this otherwise awesome library? Having been involved in open source for close to 20 years, I totally understand a "looking for help" position; but not so much the "not planning on it" position.
Maybe I just misunderstand your response...

**Comment by erizzo** [comment]
By the way, to help others getting started, I discovered this little example of using a Jackson mix-in to implement (der)serialization of Interval. It's easily adapted to other ThreeTen types (I did it quickly for LocalDateRange).
https://gist.github.com/bcalmac/4c426f3155ef6d93fe985600ab169883

**Comment by jodastephen** [comment]
My view is that integrations with other projects should be outside this repo. I'm happy to provide a link if such a repo appears. But obviously if its outside this repo, there isn't much more to do on this ticket!
