### ISSUE TITLE
Support NRF accounting calendar

### ISSUE THREAD

**Issue by lwhite1** [ThreeTen/threeten-extra#201]
Hi, I may just be missing something, but I'm trying to use the AccountingChronology to create a calendar that matches the (US) National Retail Federation calendar, a 454 calendar, ending the year on the last Saturday in January: https://nrf.com/resources/4-5-4-calendar.

I setup my chronology as follows
```

        AccountingChronology nrfChronology = new AccountingChronologyBuilder()
                .endsOn(DayOfWeek.SATURDAY) 
               
 .withDivision(AccountingYearDivision.QUARTERS_OF_PATTERN_4_5_4_WEEKS) 
                .inLastWeekOf(Month.JANUARY) 
                .leapWeekInMonth(1)
                .toChronology();
```
Everything seems ok, except the next Federation leap year is 2023, but my chronology has leap years in 2021 and 2026.  Is there something I can do to shift the leap year?

**Comment by Clockwork-Muse** [comment]
> If, after laying out the entire 52-week calendar for any given year, there are four or more days left in January during the 53rd week, then a 53rd week is added

This should be [`nearestEndOf`](https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/chrono/AccountingChronologyBuilder.html#nearestEndOf(java.time.Month)).

**Comment by lwhite1** [comment]
@Clockwork-Muse Thank you very much for your help. This is much better. 

The remaining issue is that what the retail federation (and, I think, most people) think of as the accounting year 2023 is presented as 2024 using the AccountingChronology. 

Printing the leap years, I see: 

```
Year 2013 is a leap year: true
Year 2018 is a leap year: true
Year 2024 is a leap year: true
```
Whereas the NRF page identifies the leap years as 2012, 2017, and 2023.  

It seems that the leap week is added to Jan 2024 (the end of fiscal year 2023) as expected, but the years are numbered differently. 

Printing a list of AccountingDate objects created using year and day-of-year along with the associated LocalDate, I see: 

```
Accounting date: 2024-01 maps to local date: 2023-01-29
Accounting date: 2024-02 maps to local date: 2023-01-30
etc. 
```
I would have expected the local date associated with the first day of the accounting calendar for 2024 to be Feb 4, 2024. 

Is there any way to adjust that?

**Comment by Clockwork-Muse** [comment]
Not currently, although it could be added.
It's like this because when I wrote it I was only aware of calendars that ended in the given year (so fiscal year 2024 ended in 2024).

**Comment by lwhite1** [comment]
If you could do that it would be greatly appreciated. I was thinking about hacking around it by manually adjusting the years before returning them to the user, but that seems like it would lead to all kinds of bugs I can't even imagine.

**Comment by Clockwork-Muse** [comment]
I'm working on this, but it might be a while.

**Comment by lwhite1** [comment]
that's great. thank you.  

Are you thinking of something along the lines of letting the user pick the calendar year of the start or end date?

**Comment by Clockwork-Muse** [comment]
There's essentially two versions possible:
 - Assume either the year either starts or ends in the same indexed Gregorian calendar year (boolean flag)
 - Allow for an arbitrary offset (integer, current offset of 0)

Both work for maintaining backwards compatibility.  Strictly speaking, there's some potential for confusion if the option `.nearestEndOf(Month.December)` is specified, since the end of the year is sometimes in a matching indexed year, and sometimes not... although this true already anyways.

Under the covers, this is best implemented via an offset number of years, but from a user perspective boolean flag methods to set a `-1`/`0` offset likely covers the 99% use case.  Probably something like:
 - `accountingYearEndsInGregorianYear()` (current behavior, 0 offset)
 - `accountingYearStartsInGregorianYear()` (new behavior, -1 offset)

@jodastephen - Thoughts on naming/anything here?

**Comment by jodastephen** [comment]
Your suggestion sounds about right, but Iso, not Gregorian - `accountingYearEndsInIsoYear` and `accountingYearStartsInIsoYear`
