### ISSUE TITLE
Support for the date part of an ISO 8601 time interval

### ISSUE THREAD

**Issue by akkie** [ThreeTen/threeten-extra#70]
I'm not really sure if this is a bug or if this is the expected behavior. I try to parse the ISO 8601 time interval "2007-03-01T13:00:00Z/P1Y2M10DT2H30M" as noted in the [Wikepedia page](https://en.wikipedia.org/wiki/ISO_8601#Time_intervals). This is not possible with the current `Interval` implementation, because it doesn't support the date part of the interval. If I remove the date part, then it works as expected.

```Scala
Interval.parse("2007-03-01T13:00:00Z/P1Y2M10DT2H30M") // Fails
Interval.parse("2007-03-01T13:00:00Z/PT2H30M") // Works
```

It seems that the issue comes from the fact that the `java.time.Duration` class cannot parse this format. It seems that the current Java implementations uses two classes to represent the [ISO 8601 duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations). The `java.time.Period` class can parse the date part and the `java.time.Duration` class can parse the time part.

I'm not really sure if this is wrong documented on the Wikipedia page, or if this is an issue in the library. Anyway, the `org.joda.time.Interval` does parse the string with the date part "2007-03-01T13:00:00Z/P1Y2M10DT2H30M".

**Comment by MenoData** [comment]
Not a bug, just an API-limitation (expected behaviour as [documented](http://www.threeten.org/threeten-extra/apidocs/org/threeten/extra/Interval.html#parse-java.lang.CharSequence-)).

> 
> public static Interval parse(CharSequence text)
> 
> Obtains an instance of Interval from a text string such as 2007-12-03T10:15:30Z/2007-12-04T10:15:30Z. 
> The string must consist of one of the following three formats: 
>
> •a representations of an Instant, followed by a forward slash, followed by a representation of a Instant 
> •a representation of an Instant, followed by a forward slash, followed by a representation of a Duration 
> •a representation of a Duration, followed by a forward slash, followed by a representation of an Instant 
> 

Personally I think that such a question is probably better located at Stackoverflow to get more detailed answers and to reach a broader audience. I am also not sure how far this project will go to implement all the many ISO-8601-features (not always easy to implement!), see [examples](http://time4j.net/javadoc-en/net/time4j/range/MomentInterval.html#parseISO-java.lang.String-) in my interval implementation or [this old Joda-issue](https://github.com/JodaOrg/joda-time/issues/114).

**Comment by jodastephen** [comment]
Parsing additional formats would be a reasonable enhancements to ThreeTen-Extra.
